// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Reserve is the predicate function for reserve builders.
type Reserve func(*sql.Selector)

// TimeList is the predicate function for timelist builders.
type TimeList func(*sql.Selector)

// Times is the predicate function for times builders.
type Times func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
