// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"service/internal/ent/predicate"
	"service/internal/ent/timelist"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimeListQuery is the builder for querying TimeList entities.
type TimeListQuery struct {
	config
	ctx        *QueryContext
	order      []timelist.OrderOption
	inters     []Interceptor
	predicates []predicate.TimeList
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TimeListQuery builder.
func (tlq *TimeListQuery) Where(ps ...predicate.TimeList) *TimeListQuery {
	tlq.predicates = append(tlq.predicates, ps...)
	return tlq
}

// Limit the number of records to be returned by this query.
func (tlq *TimeListQuery) Limit(limit int) *TimeListQuery {
	tlq.ctx.Limit = &limit
	return tlq
}

// Offset to start from.
func (tlq *TimeListQuery) Offset(offset int) *TimeListQuery {
	tlq.ctx.Offset = &offset
	return tlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tlq *TimeListQuery) Unique(unique bool) *TimeListQuery {
	tlq.ctx.Unique = &unique
	return tlq
}

// Order specifies how the records should be ordered.
func (tlq *TimeListQuery) Order(o ...timelist.OrderOption) *TimeListQuery {
	tlq.order = append(tlq.order, o...)
	return tlq
}

// First returns the first TimeList entity from the query.
// Returns a *NotFoundError when no TimeList was found.
func (tlq *TimeListQuery) First(ctx context.Context) (*TimeList, error) {
	nodes, err := tlq.Limit(1).All(setContextOp(ctx, tlq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{timelist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tlq *TimeListQuery) FirstX(ctx context.Context) *TimeList {
	node, err := tlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TimeList ID from the query.
// Returns a *NotFoundError when no TimeList ID was found.
func (tlq *TimeListQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tlq.Limit(1).IDs(setContextOp(ctx, tlq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{timelist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tlq *TimeListQuery) FirstIDX(ctx context.Context) int64 {
	id, err := tlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TimeList entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TimeList entity is found.
// Returns a *NotFoundError when no TimeList entities are found.
func (tlq *TimeListQuery) Only(ctx context.Context) (*TimeList, error) {
	nodes, err := tlq.Limit(2).All(setContextOp(ctx, tlq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{timelist.Label}
	default:
		return nil, &NotSingularError{timelist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tlq *TimeListQuery) OnlyX(ctx context.Context) *TimeList {
	node, err := tlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TimeList ID in the query.
// Returns a *NotSingularError when more than one TimeList ID is found.
// Returns a *NotFoundError when no entities are found.
func (tlq *TimeListQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tlq.Limit(2).IDs(setContextOp(ctx, tlq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{timelist.Label}
	default:
		err = &NotSingularError{timelist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tlq *TimeListQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := tlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TimeLists.
func (tlq *TimeListQuery) All(ctx context.Context) ([]*TimeList, error) {
	ctx = setContextOp(ctx, tlq.ctx, ent.OpQueryAll)
	if err := tlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TimeList, *TimeListQuery]()
	return withInterceptors[[]*TimeList](ctx, tlq, qr, tlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tlq *TimeListQuery) AllX(ctx context.Context) []*TimeList {
	nodes, err := tlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TimeList IDs.
func (tlq *TimeListQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if tlq.ctx.Unique == nil && tlq.path != nil {
		tlq.Unique(true)
	}
	ctx = setContextOp(ctx, tlq.ctx, ent.OpQueryIDs)
	if err = tlq.Select(timelist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tlq *TimeListQuery) IDsX(ctx context.Context) []int64 {
	ids, err := tlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tlq *TimeListQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tlq.ctx, ent.OpQueryCount)
	if err := tlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tlq, querierCount[*TimeListQuery](), tlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tlq *TimeListQuery) CountX(ctx context.Context) int {
	count, err := tlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tlq *TimeListQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tlq.ctx, ent.OpQueryExist)
	switch _, err := tlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tlq *TimeListQuery) ExistX(ctx context.Context) bool {
	exist, err := tlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TimeListQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tlq *TimeListQuery) Clone() *TimeListQuery {
	if tlq == nil {
		return nil
	}
	return &TimeListQuery{
		config:     tlq.config,
		ctx:        tlq.ctx.Clone(),
		order:      append([]timelist.OrderOption{}, tlq.order...),
		inters:     append([]Interceptor{}, tlq.inters...),
		predicates: append([]predicate.TimeList{}, tlq.predicates...),
		// clone intermediate query.
		sql:  tlq.sql.Clone(),
		path: tlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt string `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TimeList.Query().
//		GroupBy(timelist.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tlq *TimeListQuery) GroupBy(field string, fields ...string) *TimeListGroupBy {
	tlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TimeListGroupBy{build: tlq}
	grbuild.flds = &tlq.ctx.Fields
	grbuild.label = timelist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt string `json:"created_at,omitempty"`
//	}
//
//	client.TimeList.Query().
//		Select(timelist.FieldCreatedAt).
//		Scan(ctx, &v)
func (tlq *TimeListQuery) Select(fields ...string) *TimeListSelect {
	tlq.ctx.Fields = append(tlq.ctx.Fields, fields...)
	sbuild := &TimeListSelect{TimeListQuery: tlq}
	sbuild.label = timelist.Label
	sbuild.flds, sbuild.scan = &tlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TimeListSelect configured with the given aggregations.
func (tlq *TimeListQuery) Aggregate(fns ...AggregateFunc) *TimeListSelect {
	return tlq.Select().Aggregate(fns...)
}

func (tlq *TimeListQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tlq); err != nil {
				return err
			}
		}
	}
	for _, f := range tlq.ctx.Fields {
		if !timelist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tlq.path != nil {
		prev, err := tlq.path(ctx)
		if err != nil {
			return err
		}
		tlq.sql = prev
	}
	return nil
}

func (tlq *TimeListQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TimeList, error) {
	var (
		nodes = []*TimeList{}
		_spec = tlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TimeList).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TimeList{config: tlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tlq *TimeListQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tlq.querySpec()
	_spec.Node.Columns = tlq.ctx.Fields
	if len(tlq.ctx.Fields) > 0 {
		_spec.Unique = tlq.ctx.Unique != nil && *tlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tlq.driver, _spec)
}

func (tlq *TimeListQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(timelist.Table, timelist.Columns, sqlgraph.NewFieldSpec(timelist.FieldID, field.TypeInt64))
	_spec.From = tlq.sql
	if unique := tlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tlq.path != nil {
		_spec.Unique = true
	}
	if fields := tlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, timelist.FieldID)
		for i := range fields {
			if fields[i] != timelist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tlq *TimeListQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tlq.driver.Dialect())
	t1 := builder.Table(timelist.Table)
	columns := tlq.ctx.Fields
	if len(columns) == 0 {
		columns = timelist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tlq.sql != nil {
		selector = tlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tlq.ctx.Unique != nil && *tlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tlq.predicates {
		p(selector)
	}
	for _, p := range tlq.order {
		p(selector)
	}
	if offset := tlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TimeListGroupBy is the group-by builder for TimeList entities.
type TimeListGroupBy struct {
	selector
	build *TimeListQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tlgb *TimeListGroupBy) Aggregate(fns ...AggregateFunc) *TimeListGroupBy {
	tlgb.fns = append(tlgb.fns, fns...)
	return tlgb
}

// Scan applies the selector query and scans the result into the given value.
func (tlgb *TimeListGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tlgb.build.ctx, ent.OpQueryGroupBy)
	if err := tlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TimeListQuery, *TimeListGroupBy](ctx, tlgb.build, tlgb, tlgb.build.inters, v)
}

func (tlgb *TimeListGroupBy) sqlScan(ctx context.Context, root *TimeListQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tlgb.fns))
	for _, fn := range tlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tlgb.flds)+len(tlgb.fns))
		for _, f := range *tlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TimeListSelect is the builder for selecting fields of TimeList entities.
type TimeListSelect struct {
	*TimeListQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tls *TimeListSelect) Aggregate(fns ...AggregateFunc) *TimeListSelect {
	tls.fns = append(tls.fns, fns...)
	return tls
}

// Scan applies the selector query and scans the result into the given value.
func (tls *TimeListSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tls.ctx, ent.OpQuerySelect)
	if err := tls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TimeListQuery, *TimeListSelect](ctx, tls.TimeListQuery, tls, tls.inters, v)
}

func (tls *TimeListSelect) sqlScan(ctx context.Context, root *TimeListQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tls.fns))
	for _, fn := range tls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
