// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"service/internal/ent/predicate"
	"service/internal/ent/timelist"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimeListDelete is the builder for deleting a TimeList entity.
type TimeListDelete struct {
	config
	hooks    []Hook
	mutation *TimeListMutation
}

// Where appends a list predicates to the TimeListDelete builder.
func (tld *TimeListDelete) Where(ps ...predicate.TimeList) *TimeListDelete {
	tld.mutation.Where(ps...)
	return tld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tld *TimeListDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tld.sqlExec, tld.mutation, tld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tld *TimeListDelete) ExecX(ctx context.Context) int {
	n, err := tld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tld *TimeListDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(timelist.Table, sqlgraph.NewFieldSpec(timelist.FieldID, field.TypeInt64))
	if ps := tld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tld.mutation.done = true
	return affected, err
}

// TimeListDeleteOne is the builder for deleting a single TimeList entity.
type TimeListDeleteOne struct {
	tld *TimeListDelete
}

// Where appends a list predicates to the TimeListDelete builder.
func (tldo *TimeListDeleteOne) Where(ps ...predicate.TimeList) *TimeListDeleteOne {
	tldo.tld.mutation.Where(ps...)
	return tldo
}

// Exec executes the deletion query.
func (tldo *TimeListDeleteOne) Exec(ctx context.Context) error {
	n, err := tldo.tld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{timelist.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tldo *TimeListDeleteOne) ExecX(ctx context.Context) {
	if err := tldo.Exec(ctx); err != nil {
		panic(err)
	}
}
