// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"service/internal/ent/timelist"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimeListCreate is the builder for creating a TimeList entity.
type TimeListCreate struct {
	config
	mutation *TimeListMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (tlc *TimeListCreate) SetCreatedAt(s string) *TimeListCreate {
	tlc.mutation.SetCreatedAt(s)
	return tlc
}

// SetUpdatedAt sets the "updated_at" field.
func (tlc *TimeListCreate) SetUpdatedAt(s string) *TimeListCreate {
	tlc.mutation.SetUpdatedAt(s)
	return tlc
}

// SetTimesID sets the "times_id" field.
func (tlc *TimeListCreate) SetTimesID(i int64) *TimeListCreate {
	tlc.mutation.SetTimesID(i)
	return tlc
}

// SetID sets the "id" field.
func (tlc *TimeListCreate) SetID(i int64) *TimeListCreate {
	tlc.mutation.SetID(i)
	return tlc
}

// Mutation returns the TimeListMutation object of the builder.
func (tlc *TimeListCreate) Mutation() *TimeListMutation {
	return tlc.mutation
}

// Save creates the TimeList in the database.
func (tlc *TimeListCreate) Save(ctx context.Context) (*TimeList, error) {
	return withHooks(ctx, tlc.sqlSave, tlc.mutation, tlc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tlc *TimeListCreate) SaveX(ctx context.Context) *TimeList {
	v, err := tlc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tlc *TimeListCreate) Exec(ctx context.Context) error {
	_, err := tlc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tlc *TimeListCreate) ExecX(ctx context.Context) {
	if err := tlc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tlc *TimeListCreate) check() error {
	if _, ok := tlc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TimeList.created_at"`)}
	}
	if _, ok := tlc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TimeList.updated_at"`)}
	}
	if _, ok := tlc.mutation.TimesID(); !ok {
		return &ValidationError{Name: "times_id", err: errors.New(`ent: missing required field "TimeList.times_id"`)}
	}
	return nil
}

func (tlc *TimeListCreate) sqlSave(ctx context.Context) (*TimeList, error) {
	if err := tlc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tlc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tlc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	tlc.mutation.id = &_node.ID
	tlc.mutation.done = true
	return _node, nil
}

func (tlc *TimeListCreate) createSpec() (*TimeList, *sqlgraph.CreateSpec) {
	var (
		_node = &TimeList{config: tlc.config}
		_spec = sqlgraph.NewCreateSpec(timelist.Table, sqlgraph.NewFieldSpec(timelist.FieldID, field.TypeInt64))
	)
	if id, ok := tlc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tlc.mutation.CreatedAt(); ok {
		_spec.SetField(timelist.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := tlc.mutation.UpdatedAt(); ok {
		_spec.SetField(timelist.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if value, ok := tlc.mutation.TimesID(); ok {
		_spec.SetField(timelist.FieldTimesID, field.TypeInt64, value)
		_node.TimesID = value
	}
	return _node, _spec
}

// TimeListCreateBulk is the builder for creating many TimeList entities in bulk.
type TimeListCreateBulk struct {
	config
	err      error
	builders []*TimeListCreate
}

// Save creates the TimeList entities in the database.
func (tlcb *TimeListCreateBulk) Save(ctx context.Context) ([]*TimeList, error) {
	if tlcb.err != nil {
		return nil, tlcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tlcb.builders))
	nodes := make([]*TimeList, len(tlcb.builders))
	mutators := make([]Mutator, len(tlcb.builders))
	for i := range tlcb.builders {
		func(i int, root context.Context) {
			builder := tlcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TimeListMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tlcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tlcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tlcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tlcb *TimeListCreateBulk) SaveX(ctx context.Context) []*TimeList {
	v, err := tlcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tlcb *TimeListCreateBulk) Exec(ctx context.Context) error {
	_, err := tlcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tlcb *TimeListCreateBulk) ExecX(ctx context.Context) {
	if err := tlcb.Exec(ctx); err != nil {
		panic(err)
	}
}
